### ISSUE TITLE
Support "Read Only" mode like OpenAnnotate does

### ISSUE THREAD

**Issue by benallenallen** [tsgrp/OpenAnnotateVideo#1]
Currently, we make a call at the very beginning of OA to the "canRelate" endpoint, that tells us if we should be in a "readOnly" mode. We need to have this same functionality in OAV to prevent users that shouldn't be able to create new annotations from getting an error if they try to annotate.

**Comment by cchau-tsgrp** [comment]
@acastor did you fix it already? If so can you close this ticket for me?
(btw we will start using GitHub now to track everything.)

**Comment by acastor** [comment]
Closed by Revisions 333 and 335; CR by Chris
